services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    container_name: ns-fastapi-app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
    # restart: unless-stopped